// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Recall.Web.Infrastructure.Persistence;

#nullable disable

namespace Recall.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902131902_AddUserLikes")]
    partial class AddUserLikes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.AppUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.CachedEpisodeExtendedEntity", b =>
                {
                    b.Property<int>("EpisodeTvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_tvdb_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_utc");

                    b.Property<int?>("SeriesTvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("series_tvdb_id");

                    b.HasKey("EpisodeTvdbId");

                    b.ToTable("cached_episode_extended", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.CachedSeriesAggregateEntity", b =>
                {
                    b.Property<int>("TvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tvdb_id");

                    b.Property<string>("Language")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("language");

                    b.Property<bool?>("KeepUpdated")
                        .HasColumnType("boolean")
                        .HasColumnName("keep_updated");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_utc");

                    b.Property<string>("StatusName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status_name");

                    b.HasKey("TvdbId", "Language");

                    b.ToTable("cached_series_aggregate", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.CachedSeriesExtendedEntity", b =>
                {
                    b.Property<int>("TvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tvdb_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_utc");

                    b.HasKey("TvdbId");

                    b.ToTable("cached_series_extended", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.CachedSeriesOmdbEntity", b =>
                {
                    b.Property<int>("TvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tvdb_id");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("imdb_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_utc");

                    b.HasKey("TvdbId");

                    b.HasIndex("RetrievedUtc")
                        .HasDatabaseName("ix_cached_series_omdb_retrieved_utc");

                    b.ToTable("cached_series_omdb", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.EmailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("text")
                        .HasColumnName("html_body");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<int>("SendAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("send_attempts");

                    b.Property<DateTime?>("SentUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_utc");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("to_address");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("Id");

                    b.HasIndex("SentUtc", "Priority", "CreatedUtc")
                        .HasDatabaseName("ix_email_pending");

                    b.ToTable("email", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.EpisodeWatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<int>("EpisodeTvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("episode_tvdb_id");

                    b.Property<int>("SeriesTvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("series_tvdb_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("WatchedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("watched_utc");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EpisodeTvdbId")
                        .IsUnique();

                    b.HasIndex("UserId", "SeriesTvdbId");

                    b.ToTable("episode_watch", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.LoginTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConsumedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_utc");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<DateTime>("ExpiresUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_utc");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ConsumedUtc");

                    b.ToTable("login_token", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.TrackedSeriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<DateOnly?>("FirstAired")
                        .HasColumnType("date")
                        .HasColumnName("first_aired");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("Overview")
                        .HasColumnType("text")
                        .HasColumnName("overview");

                    b.Property<int>("TvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("tvdb_id");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TvdbId")
                        .IsUnique();

                    b.ToTable("tracked_series", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.UserLikeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<int>("SeriesTvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("series_tvdb_id");

                    b.Property<int>("TargetTvdbId")
                        .HasColumnType("integer")
                        .HasColumnName("target_tvdb_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("target_type");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetTvdbId");

                    b.HasIndex("UserId", "SeriesTvdbId");

                    b.HasIndex("UserId", "TargetType");

                    b.HasIndex("UserId", "TargetType", "TargetTvdbId")
                        .IsUnique();

                    b.ToTable("user_like", (string)null);
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.EpisodeWatchEntity", b =>
                {
                    b.HasOne("Recall.Web.Infrastructure.Persistence.Entities.AppUserEntity", "User")
                        .WithMany("EpisodeWatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.LoginTokenEntity", b =>
                {
                    b.HasOne("Recall.Web.Infrastructure.Persistence.Entities.AppUserEntity", "User")
                        .WithMany("LoginTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.TrackedSeriesEntity", b =>
                {
                    b.HasOne("Recall.Web.Infrastructure.Persistence.Entities.AppUserEntity", "User")
                        .WithMany("TrackedSeries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.UserLikeEntity", b =>
                {
                    b.HasOne("Recall.Web.Infrastructure.Persistence.Entities.AppUserEntity", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Recall.Web.Infrastructure.Persistence.Entities.AppUserEntity", b =>
                {
                    b.Navigation("EpisodeWatches");

                    b.Navigation("Likes");

                    b.Navigation("LoginTokens");

                    b.Navigation("TrackedSeries");
                });
#pragma warning restore 612, 618
        }
    }
}
